# Generated by Django 5.0.4 on 2026-03-11 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_debtor_risk_factors_debtor_risk_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creditor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('bank', 'Bank'), ('fintech', 'Fintech'), ('telecom', 'Telecom'), ('utilities', 'Utilities'), ('retail', 'Retail'), ('sme', 'SME'), ('other', 'Other')], default='other', max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditor_category', models.CharField(choices=[('bank', 'Bank'), ('fintech', 'Fintech'), ('telecom', 'Telecom'), ('utilities', 'Utilities'), ('retail', 'Retail'), ('sme', 'SME'), ('other', 'Other')], default='other', max_length=20)),
                ('product_type', models.CharField(blank=True, max_length=100)),
                ('dpd_band', models.CharField(max_length=50)),
                ('balance_band', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('avg_recovery_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('avg_contact_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_ptp_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('avg_conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('sample_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='benchmarks', to='valuation.creditor')),
            ],
            options={
                'ordering': ('-sample_size', '-avg_recovery_rate'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reporting_currency', models.CharField(default='EUR', max_length=3)),
                ('source_file_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_batches', to='valuation.creditor')),
                ('portfolio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_batch', to='portfolio.portfolio')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PortfolioValuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_recovery_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expected_collections', models.DecimalField(decimal_places=2, max_digits=14)),
                ('recommended_bid_pct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recommended_bid_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_roi', models.DecimalField(decimal_places=2, max_digits=7)),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valuation_method', models.CharField(choices=[('rule_based', 'Rule Based'), ('benchmark', 'Benchmark'), ('hybrid', 'Hybrid'), ('ml', 'ML')], default='rule_based', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_valuations', to=settings.AUTH_USER_MODEL)),
                ('creditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='valuation.creditor')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='portfolio.portfolio')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuations', to='valuation.portfoliouploadbatch')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ModelPredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=50)),
                ('prediction_type', models.CharField(choices=[('recovery_rate', 'Recovery Rate'), ('expected_collections', 'Expected Collections'), ('bid_pct', 'Bid Percentage'), ('roi', 'ROI')], max_length=30)),
                ('prediction_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prediction_logs', to='portfolio.portfolio')),
                ('valuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_logs', to='valuation.portfoliovaluation')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ValuationFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=100)),
                ('factor_weight', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('factor_value', models.CharField(blank=True, max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('valuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factors', to='valuation.portfoliovaluation')),
            ],
            options={
                'ordering': ('-factor_weight', 'factor_name'),
            },
        ),
    ]
