# Generated by Django 5.0.4 on 2026-03-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_dataimportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='risk_factors',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='debtor',
            name='risk_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
