# Generated by Django 5.0.4 on 2026-03-14 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0003_debtor_risk_factors_debtor_risk_score'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('risk_band', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('debtor_status', models.CharField(blank=True, max_length=40)),
                ('dpd_min', models.PositiveIntegerField(default=0)),
                ('dpd_max', models.PositiveIntegerField(default=9999)),
                ('requires_phone', models.BooleanField(default=False)),
                ('requires_email', models.BooleanField(default=False)),
                ('recommended_action', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('email', 'Email'), ('settlement', 'Settlement Offer'), ('legal_review', 'Legal Review'), ('field_visit', 'Field Visit'), ('monitor', 'Monitor')], max_length=30)),
                ('recommended_channel', models.CharField(blank=True, choices=[('call', 'Call'), ('sms', 'SMS'), ('email', 'Email'), ('settlement', 'Settlement Offer'), ('legal_review', 'Legal Review'), ('field_visit', 'Field Visit'), ('monitor', 'Monitor')], max_length=30)),
                ('base_uplift_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('priority_weight', models.PositiveSmallIntegerField(default=50)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ActionScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('email', 'Email'), ('settlement', 'Settlement Offer'), ('legal_review', 'Legal Review'), ('field_visit', 'Field Visit'), ('monitor', 'Monitor')], max_length=30)),
                ('expected_recovery_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('expected_recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_uplift_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estimated_roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_scenarios', to='portfolio.debtor')),
            ],
            options={
                'ordering': ('debtor', 'action_type', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='DebtorActionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_action', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('email', 'Email'), ('settlement', 'Settlement Offer'), ('legal_review', 'Legal Review'), ('field_visit', 'Field Visit'), ('monitor', 'Monitor')], max_length=30)),
                ('recommended_channel', models.CharField(blank=True, choices=[('call', 'Call'), ('sms', 'SMS'), ('email', 'Email'), ('settlement', 'Settlement Offer'), ('legal_review', 'Legal Review'), ('field_visit', 'Field Visit'), ('monitor', 'Monitor')], max_length=30)),
                ('priority_score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expected_uplift_pct', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('expected_uplift_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reason_summary', models.TextField(blank=True)),
                ('model_version', models.CharField(default='strategy-rules-v1', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_recommendations', to='portfolio.debtor')),
                ('source_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='strategy.actionrule')),
            ],
            options={
                'ordering': ('-priority_score', '-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StrategyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('strategy_type', models.CharField(choices=[('call_first', 'Call-First'), ('digital_first', 'Digital-First'), ('settlement_first', 'Settlement-First'), ('legal_escalation', 'Legal Escalation'), ('balanced', 'Balanced Mix')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='strategy_runs', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_runs', to='portfolio.portfolio')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StrategyRunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_count', models.PositiveIntegerField(default=0)),
                ('expected_total_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_total_uplift', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expected_roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('strategy_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='strategy.strategyrun')),
            ],
            options={
                'ordering': ('-strategy_run__created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CollectorQueueAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collector_name', models.CharField(max_length=120)),
                ('priority_rank', models.PositiveIntegerField()),
                ('action_type', models.CharField(choices=[('call', 'Call'), ('sms', 'SMS'), ('email', 'Email'), ('settlement', 'Settlement Offer'), ('legal_review', 'Legal Review'), ('field_visit', 'Field Visit'), ('monitor', 'Monitor')], max_length=30)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='queued', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collector_queue_assignments', to='portfolio.debtor')),
            ],
            options={
                'ordering': ('priority_rank', '-assigned_at', '-id'),
                'unique_together': {('collector_name', 'priority_rank')},
            },
        ),
    ]
